### ISSUE TITLE
Fix infection event (age dependency)

### ISSUE THREAD

**Issue by SaraJakubiak** [magicicada/slim#10]
The infection event is dependent on the life stage (L2) and time spent in that stage (need more information on the exact dependency). Since we do not hold the ages for each lice, how to model that age dependency?

See do_infection_events in Cage.

**Comment by erolm-a** [comment]
The original code seems to take into account the arrival of a louse onto a specific cage (which _might not_ be the one in which it developed previously) and defines the expected travel time [here](https://github.com/magicicada/slim/blob/7947444332a854d5b58eadf3644a54d6c75ce129/original/Data/Edays.csv). While Aldrin suggests that infection can happen at any time as long as age >= 1, here it assumes it always takes 7 days to travel for a louse.

As a consequence, it is safe _for now_ to only allow infection from the 7th day onward.

**Comment by erolm-a** [comment]
After some reviewing it turned out I was partially wrong: the data are taken from Fyne_edays.csv (but are still somewhat centered around 7) and the arrival date refers to the transportation time of eggs across... farms? Not sure if farm-to-farm movement is the same of cage-to-cage.
For now, the only assumption I would make is that infection can only happen from the second day on.

**Comment by magicicada** [comment]
Farm-to-farm movement is definitely a thing that we want happening - it's likely to be really important when we get to the part of the project where we model different farms using different treatment approaches, and is the part that includes matrices for movement between different sites in a sea loch.  

I guess we should think about where that farm-to-farm movement should live in the code.  In SeaLiceMgmt?

**Comment by erolm-a** [comment]
Closing this as the original issue (age dependency) can be safely deemed as closed for now.
