### ISSUE TITLE
Investigate differences between Stien's (currently implemented) and Aldrin's approaches

### ISSUE THREAD

**Issue by erolm-a** [magicicada/slim#23]
For what concerns natural death, Stien's approach is based on a Poisson-based event generation of "deaths" while Aldrin's approach relies on a first-order autoregressive model.

Treatment mortality code roughly follows Aldrin approach but it doesn't take temperatures into account. Some refactoring would be needed to make them accessible to the whole `Cage` class.

There are a number of discrepancies between the hardcoded assumption in the code (14-day delay followed by a _hardcoded_ duration) and Aldrin's paper (5-day delay for EMB followed by a temperature-based duration). If Aldrin's numbers are correct then our model always assumes we're working at around 6 °C, but both Ardrishaig and Tarbert have quite higher (~11 °C) means.

(Some commentary on other approaches will follow here)

**Comment by magicicada** [comment]
As discussed in meetings and on chat, your approach seems sensible.  Previous implementation probably chosen for ease of implementation rather than to be a consistent model.
